spring:
  cloud:
    gateway:
      routes:
        - id: taskcalendar
          uri: lb://TASKCALENDAR-SERVICE
          #          uri: lb://localhost:8088/
          predicates:
            - Path=/api/taskcalendar/**
        - id: employee
          #          uri: lb://localhost:8082/
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employee/**, /api/teams/**
#            - Path=/api/teams/**

      globalcors:
        corsConfigurations:
          '[/**]':
            #           allowedOrigins: "*"
            allowedOrigins: "https://progasoffice.netlify.app"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
              - PUT


#
#      default-filters:
#        - name: Retry
#          args:
#            retries: 3
#            metchods: GET
#            series: SERVER_ERROR
#            #            exceptions: java.io.IOException  - można wybrać wyjątki
#            backoff:
#              firstBackoff: 50ms
#              maxBackOff: 500ms
#              factor: 2
#              basedOnPreviousValue: false