
spring:
  cloud:
    gateway:
      routes:
        - id: taskcalendar
          uri: lb://TASK-CALENDAR-SERVICE
#          uri: lb://localhost:8088/
          predicates:
            - Path=/api/taskcalendar/**
        - id: teams
#          uri: lb://localhost:8082/
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/teams/**

      globalcors:
        corsConfigurations:
         '[/**]':
           allowedOrigins: "*"
           allowedMethods:
              - GET
              - POST
              - PUT